<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <IsPackable>True</IsPackable>
    <RootNamespace>Avalonia.Controls</RootNamespace>
    <PackageId>Avalonia.Controls.TreeDataGrid</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.8" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
</Project>
